/**
 * End-to-end demo:
 *
 *   1. Owner writes a rule in plain English.
 *   2. @sentinel/ai compiles it into a PolicySpec.
 *   3. @sentinel/sdk initializes the policy on-chain.
 *   4. A mock "AI trading agent" calls sentinel.guard() before each trade.
 *   5. Watch benign trades pass, over-limit trades get blocked, and a
 *      large trade get escalated → approved by owner → executed.
 *
 * Run against localnet: `solana-test-validator` in another terminal, then
 * `pnpm --filter @sentinel/demo start`.
 */

import {
  Connection,
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
} from "@solana/web3.js";
import { AnchorProvider, Wallet } from "@coral-xyz/anchor";
import {
  Sentinel,
  KNOWN_PROGRAMS,
  derivePolicyPda,
  deriveTicketPda,
} from "@sentinel/sdk";
import { compileOffline, PolicyCompiler } from "@sentinel/ai";

// IDL is generated by `anchor build` into target/idl/sentinel.json.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const idl = require("../../target/idl/sentinel.json");

async function airdrop(c: Connection, pk: PublicKey, sol = 2) {
  const sig = await c.requestAirdrop(pk, sol * LAMPORTS_PER_SOL);
  await c.confirmTransaction(sig);
}

async function main() {
  const connection = new Connection("http://127.0.0.1:8899", "confirmed");

  const ownerKp = Keypair.generate();
  const agentKp = Keypair.generate();
  await airdrop(connection, ownerKp.publicKey);
  await airdrop(connection, agentKp.publicKey);

  const ownerWallet = new Wallet(ownerKp);

  // 1. Plain English rule. Notice the thresholds form a coherent policy:
  //    per_tx (100) > escalation (50), so any trade in [50,100] USDC is
  //    allowed only with an owner-issued escalation ticket.
  const rule =
    "my agent trades on Jupiter with a maximum of 500 USDC per hour, " +
    "max 100 USDC per tx, and escalate above 50 USDC";

  // 2. Compile (offline fallback — no API key needed).
  const spec = process.env.ANTHROPIC_API_KEY
    ? await new PolicyCompiler({ apiKey: process.env.ANTHROPIC_API_KEY }).compile(rule)
    : compileOffline(rule);

  console.log("Compiled policy:", {
    maxPerTx: spec.maxPerTx.toString(),
    maxPerHour: spec.maxPerHour.toString(),
    escalationThreshold: spec.escalationThreshold.toString(),
    whitelist: spec.whitelist.map((p) => p.toBase58()),
  });

  // 3. Initialize on-chain.
  const { sentinel } = await Sentinel.initialize(
    connection,
    ownerWallet,
    agentKp.publicKey,
    spec,
    idl,
  );
  console.log("Policy PDA:", sentinel.policy.toBase58());

  // Rebuild Sentinel client under the AGENT's wallet for guard calls.
  const agentProvider = new AnchorProvider(connection, new Wallet(agentKp), {
    commitment: "confirmed",
  });
  const agentSentinel = await Sentinel.load(
    connection,
    new Wallet(agentKp),
    sentinel.policy,
    idl,
  );

  const JUP = KNOWN_PROGRAMS.JUPITER;
  const RAY = KNOWN_PROGRAMS.RAYDIUM_AMM;

  const USDC = 1_000_000n; // 6 decimals

  // 4a. Small benign swap — passes both caps + whitelist.
  console.log("\n[agent] swap 25 USDC on Jupiter…");
  await agentSentinel.guard({ amount: 25n * USDC, targetProgram: JUP });
  console.log("  ✅ approved");

  // 4b. Agent tries Raydium (not whitelisted) — blocked at guardrail #2.
  console.log("\n[agent] swap 10 USDC on Raydium…");
  try {
    await agentSentinel.guard({ amount: 10n * USDC, targetProgram: RAY });
  } catch (e: any) {
    console.log("  ⛔ blocked:", e.error?.errorMessage ?? e.message);
  }

  // 4c. Over per-tx cap — blocked at guardrail #1a.
  console.log("\n[agent] swap 150 USDC on Jupiter…");
  try {
    await agentSentinel.guard({ amount: 150n * USDC, targetProgram: JUP });
  } catch (e: any) {
    console.log("  ⛔ blocked:", e.error?.errorMessage ?? e.message);
  }

  // 4d. 75 USDC — under per-tx cap (100) but over escalation threshold
  //     (50). Must be held for owner approval (guardrail #4).
  const big = 75n * USDC;
  console.log(`\n[agent] swap 75 USDC on Jupiter (needs escalation)…`);
  try {
    await agentSentinel.guard({ amount: big, targetProgram: JUP });
  } catch (e: any) {
    console.log("  ⏸  held:", e.error?.errorMessage ?? e.message);
  }
  console.log("[owner] approving escalation ticket…");
  const { ticket } = await sentinel.approveEscalation(big, JUP, 600);
  console.log("[agent] retrying swap with ticket…");
  await agentSentinel.guard({ amount: big, targetProgram: JUP, escalationTicket: ticket });
  console.log("  ✅ approved");

  // 4e. Drive the rolling hourly cap. Already spent 25 + 75 = 100 USDC.
  //     Cap is 500, so 4 more 100-USDC swaps = 500 (still ok), and the
  //     next one (making 600) trips guardrail #1b.
  console.log("\n[agent] four back-to-back 100 USDC Jupiter swaps…");
  for (let i = 0; i < 4; i++) {
    await agentSentinel.guard({ amount: 100n * USDC, targetProgram: JUP });
  }
  console.log("  ✅ 4/4 approved (window_spent = 500 USDC)");
  console.log("[agent] one more 100 USDC swap — should trip hourly cap…");
  try {
    await agentSentinel.guard({ amount: 100n * USDC, targetProgram: JUP });
  } catch (e: any) {
    console.log("  ⛔ blocked:", e.error?.errorMessage ?? e.message);
  }

  // 5. Final state.
  const state = await agentSentinel.fetchState();
  console.log("\nFinal policy state:", {
    totalActions: state.totalActions.toString(),
    totalBlocked: state.totalBlocked.toString(),
    windowSpent: state.windowSpent.toString(),
  });
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
